### ISSUE TITLE
Integrate this lib with backtrader to support any timeframe candles

### ISSUE THREAD

**Issue by sefgit** [fja05680/pinkfish#14]
Pleae add support of M1, M5, i.e. faster timeframe candles.
Integration in backtrader would be nice too.

I was thinking something similiar to 
https://github.com/Oxylo/btreport
or
https://www.backtrader.com/docu/analyzers/pyfolio/

**Comment by fja05680** [comment]
Hi sefgit,

Pinkfish only supports daily data, and I don't plan on extending it to other time frames.

I added an examples demonstrating how to Integrate Pinkfish with Quantopian's pyfolio and empyrical analytical.  As the examples show, this was pretty easy to achieve.  Please see examples/pyfolio-empyrical

cheers,
Farrell

**Comment by sefgit** [comment]
Thank you, Farrell, for your reply.
I really appreciate for the update.

cheers,
sef
