### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dans-acc** [fja05680/pinkfish#17]
Hello,

I was wondering, say you priovided your own minute OHLC data. Would it still be possible to back test strategies, or is this library exclusively written for daily OHLC?

Best,

Dans.

**Comment by fja05680** [comment]
Hi Dans.

If the format of the csv file match, the backtest may actually run.  The statistics is completely coded around daily data though.  I hate to tell people to look elsewhere, but currently Pinkfish is not a good option for minute data.

Thanks for checking out Pinkfish,
Farrell

**Comment by dans-acc** [comment]
Hello,

Daily support will suffice for the time being - I enjoy the simplicity of the library.

I thought you might say that, it did cross my mind to maybe fork it at a later date (when needed) and make the necessary contributions.

Best,

Dans

**Comment by lorrp1** [comment]
@fja05680 id be interested too in using hour/minute data, if you plan to make any "upgrade" consider it please since i really prefer this library over all the other i have seen.

**Comment by fja05680** [comment]
lorrp1, thanks for your kind words and checking out pinkfish.  I think the major issue is with the statistics.  I have successfully integrated pinkfish with other statistics libraries, so perhaps a path forward is getting trading to work on a minute/hour basis and use a third party for the statistics.  When I get a chance I'll see what's really involved.

**Comment by lorrp1** [comment]
@fja05680 also i think a documentation would be way easier to read and understand than video

**Comment by fja05680** [comment]
lorrp1, thank your for this feedback.  A problem I have with documentation is that it often gets out of sync with the source.  To overcome this obstacle, I'm going to start with adding better comments into the code.  There are automatic documentation generators that can be used from there.  Another option is to work within the Python system like TA-Lib does and provide the documentation via python calls.  A general user guide is something that I could do at some point.  I'm also very open to someone else doing this.  If someone else wants to document pinkfish, I'm more than willing to work with them.  I feel that a strength of pinkfish are the numerous examples.  All pinkfish functionality is in one or more of the examples.  This was a major problem when I tried to use other libraries.  Usually, you get a single moving average crossover example and that's it.

**Comment by lorrp1** [comment]
@fja05680 im getting the annual return of the spy benchmark at 16 annual now unlike yesterday  when i got 13

**Comment by fja05680** [comment]
Hello,
16.1% CAGR is correct.  You can verify it using this link:
https://www.thecalculatorsite.com/finance/calculators/cagr-calculator.php

In the future, please open a new issue instead of adding to this one.  Thanks!
