### ISSUE TITLE
feature: Can we save plots to files?

### ISSUE THREAD

**Issue by tombohub** [fja05680/pinkfish#20]
Instead of displaying them is there a method to save them to file?
Thank you

**Comment by fja05680** [comment]
Hello, It appears that it would be easy to save them to file in addition to
displaying the plots.  I can add this enhancement pretty quickly.  I'll try
to get it merged by tomorrow.  You can also save the entire notebook to a
PDF file.  Just print from the browser to a PDF file.

It may require more effort to not get them to plot at all but only write to
a file.

Farrell

**Comment by fja05680** [comment]
There is an optional parameter, namely "fname" that can be passed to any of the functions in plot.py.  See example/buy-hold-dividends.ipynb or an example.
