### ISSUE TITLE
can we use our own data?

### ISSUE THREAD

**Issue by tombohub** [fja05680/pinkfish#21]
I am looking, can't find, how can we use our own dataframes?

**Comment by fja05680** [comment]
Hello, I think you are asking if you can supply your own timeseries for a symbol (stock or etf).  The answer to that question is yes.  The data needs to be in a CSV file and use same format as timeseries from yahoo finance.  Put the file into your data folder, which will either be in the same folder as your project, or the one specified in the config file (if you set one up).  For the fetch command, set use_cache=True (this is actually the default).  Please let me know if this helped.  Thanks, Farrell

**Comment by tombohub** [comment]
Does that mean CSV has to be exactly the same as yahoo finance or we can have extra columns in our CSV?
This helps, thank you, I appreciate your answers!

**Comment by fja05680** [comment]
tombohub,

Any extra fields will be ignored.

**Comment by tombohub** [comment]
I understand, thank you!

**Comment by tombohub** [comment]
I am leaving this for future visitors:

You can use your own DataFrame, for example with yfinance:

```python
stock = yf.Ticker('spy')
ts = stock.history(period='1mo')
ts.columns = ts.columns.str.lower()
```
and do your strategy with `ts`

**Comment by fja05680** [comment]
I recommend that you get all of the data, i.e. ts = stock.history(period='max'), then control the timeframe with the start and end variables, i.e. ts = select_tradeperiod(ts, start, end)
