### ISSUE TITLE
what is drawdown_recovery ?

### ISSUE THREAD

**Issue by tombohub** [fja05680/pinkfish#23]
Hello,

I am trying to figure out what this stat represent.

As I can see it seems to be difference in years between `max_closed_out_drawdown_end_date` and `max_closed_out_drawdown_start_date`.

And the result is something like : `-0.25`

My question is, why those two dates and why not difference between `max_closed_out_drawdown_recovery_date` and `max_closed_out_drawdown_end_date` ?

And why is the value negative?

Thanks

**Comment by fja05680** [comment]
tombohub, good points.  What I have is properly called loss-recovery-period, which covers both the loss-period and the reovery-period.  I'm thinking of including all three, i.e.
 drawdown_loss_recovery_period
 drawdown_loss_period
 drawdown_recovery_period

I agree, they should all be positive.  How does that sound?

**Comment by fja05680** [comment]
tombohub,

I just merged a fix for this issue.  Now there is
stats['drawdown_loss_period']
stats['drawdown_recovery_period']
stats['annualized_return_over_max_drawdown']

See double-7s example which I updated to demonstrate this fix.

Thanks for pointing this out these issues with drawdown stastics.  Farrell

**Comment by tombohub** [comment]
@fja05680 that sounds good!

Me personally I would like to see that numbers in days or months. It seems more easier to reason than for example 0.25years.
But, it's your decision, we can always manipulate in excel or code if needed.

no problem, thank for fixing it so quick

**Comment by fja05680** [comment]
Thanks.  It is in days.  Will actually print 284 days, for example.
