### ISSUE TITLE
is there an option to backtest, but without money?

### ISSUE THREAD

**Issue by tombohub** [fja05680/pinkfish#26]
Hello,
I am interest in purely statistical performance of stock so I would like to backtest, but without using money as factor.

Because for example if stock is 6000$ and I put 10000$ capital it will trade only one stock and all the returns stats based on inital capital will not be same as real performance , right? 

I can use large capital like 1.000.000 or something, but just in case - 
do you have some hidden option to trade without money?

**Comment by fja05680** [comment]
Good question.  Sorry, I there isn't a mode that trades without cash.  As you pointed out, you can get very close to the statistical result by using a large amount of cash, like a billion.  You an print out a custom summary that doesn't include any dollar amounts.

BTW - I now have a discussion tab.  Please ask your questions there, and then we can use 'Issues' for only bug reports.

cheers
