### ISSUE TITLE
Is it possible to remove dependency on TAlib?

### ISSUE THREAD

**Issue by tombohub** [fja05680/pinkfish#48]
TAlib is problematic to install on ubuntu and especially on windows which I still didn't figure out how. 

Is it possible to install and use pinkfish without TAlib?

**Comment by tombohub** [comment]
Hi, thanks I'll do that! Did you try some other indicators package? 

Great news with going to pip package, that will make installation much easier

**Comment by fja05680** [comment]
tombohub,

Thanks for bring up this issue.  I just removed the ta-lib dependency for pinkfish API.

Farrell

**Comment by paulmcq** [comment]
README.md typos??
 I still recommend that later you get ta-lib installed so that you can run
all the examples, some of which depend on pinkfish ta-lib. Also, this opens
up the likelyhood likelihood that I can soon release a pinkfish version
that can be installed with pip.

**Comment by fja05680** [comment]
Yes it should just say ta-iib not pinkfish ta-lib.  There is no such thing
as pinkfish ta-lib.  Thanks for finding this error.

**Comment by fja05680** [comment]
Yes and I noticed another typo there.  I did this in the wee hours last
night.  I'll fix it in a little bit thanks.

**Comment by paulmcq** [comment]
BTW, I agree muchly that if pinkfish was able to be installed via pip it
would help a lot.
For example, me: I have not tried pinkfish just because I do not understand
the effects on my virtualenvs if I tried to install it without using pip :-(

**Comment by fja05680** [comment]
I'll try to get a pip install within the next couple weeks.  I my even try it out on Windows.  I've been hesitant to make a pip version available for two reasons: pinkfish was under heavy development, and there was no easy way to install ta-lib.  Both of these concerns are now out of the way.
