### ISSUE TITLE
cant import pinkfish

### ISSUE THREAD

**Issue by aiot-tech** [fja05680/pinkfish#58]
Hello, when running the code below,some error occurs. Do you know what cause it?
```
(base) root@highperformancePC:/home/pinkfish# ipython 
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.31.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pinkfish
Segmentation fault (core dumped)
```
And I install the package as follow:
```
git clone https://github.com/fja05680/pinkfish.git
cd pinkfish
sudo python setup.py install
```

**Comment by fja05680** [comment]
Hello,

Which OS are you using?

**Comment by aiot-tech** [comment]
Ubuntu 16.04

**Comment by fja05680** [comment]
That version of Ubuntu bis too old and I believe uses python 2.7 which
pinkish no longer supports.  Please upgrade your os to version 20.04 or
later and try again.

**Comment by aiot-tech** [comment]
I will try it again. Thx a lot.
