### ISSUE TITLE
outdated pandas.io

### ISSUE THREAD

**Issue by harryDevPy** [fja05680/pinkfish#6]
Hello,
in fetch.py a line need to be changed:
from
from pandas.io.data import DataReader
to
from pandas_datareader import data

or it gives error importing (at least on Linux Mint 18.1)

**Comment by fja05680** [comment]
Hello,

Thanks for letting me know this.  Someone has actually submitted a pull
request for this already.  I'm too busy with finals at school so can't do
anything right now.  During Christmas break I'll get this in though.

Thanks!
Farrell

**Comment by jtromans** [comment]
Wouldn't it be 
import pandas_datareader as DataReader

**Comment by fja05680** [comment]
Finally got the pull request in that fixes this issue.  Please pull from the head to get the latest.

**Comment by fja05680** [comment]
Hello, this issue has now been fixed.
