### ISSUE TITLE
updating dependency versions in requests.txt

### ISSUE THREAD

**Issue by tombohub** [fja05680/pinkfish#77]
Hi, it seems lot of dependencies are older versions in requests.txt. Because all of them are pinned to exact version number we cannot install pinkfish using poetry, unless we downgrade packages installed before we installed pinkfish.

Error message poetry:

```
Because no versions of pinkfish match >1.16.0,<2.0.0
 and pinkfish (1.16.0) depends on requests (2.28.1), pinkfish (>=1.16.0,<2.0.0) requires requests (2.28.1).
So, because stock-analytics depends on both requests (^2.31.0) and pinkfish (^1.16.0), version solving failed.
```

which means I get requests v2.31.0 installed , but pinkfish requires exact 2.28.1 version.

How do we go with updating dependencies to at lease using carrots: ^2.28.1 ?

**Comment by fja05680** [comment]
Hi, I tried doing this once, setting a minimum version but this doesn't
work.  These packages don't always maintain backward compatibility.  So you
have to pin a specific version.  The way around this is creating a virtual
environment for pinkfish.  In my opinion this is the proper approach for
any Python project.  I'm not familiar with the tool that you mentioned, but
I assume it's capable of dealing with virtual Python environments.  I
suggest that you search that out, and use a virtual environment.

**Comment by fja05680** [comment]
Oh I see.  I'll get it updated over the Christmas break so that newer
versions are called out in requirements.txt

**Comment by fja05680** [comment]
Hi,
I update everything to newer versions and removed dependency to TA-Lib.  I'll plan to do a new release in a couple of days.  I closed your PR.  I did incorporate your suggestion to .gitignore.  I didn't change setup.py though because TA-Lib is no longer called out in requirements.txt.

**Comment by fja05680** [comment]
Release 2.1.0 created.  I looked at requirements.txt and there are is no longer a reference to talib or TA-Lib.  Also v2.31.0 is called out for requests.

**Comment by tombohub** [comment]
Hi, thank you. I was able to install without problems.

**Comment by fja05680** [comment]
Glad to hear it!
